{
    'name': 'Sistem Perpustakaan',
    'version': '1.0',
    'summary': 'Modul untuk mengelola perpustakaan',
    'description': 'Modul sederhana untuk mengelola data buku dan peminjaman perpustakaan',
    'category': 'Services/Library',
    'author': 'Nama Anda',
    'depends': ['base'],
    'data': [
        'security/library_groups.xml',
        'security/ir.model.access.csv',
        'data/library_loan_sequence.xml',
        'views/library_book_views.xml',
        'views/library_loan_views.xml',
        'views/library_menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
